//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public long PlayerId { get; set; }
        public byte AccountStatus { get; set; }
        public byte AccountPrivileges { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string IPAddress { get; set; }
        public string Avatar { get; set; }
        public string GameObjects { get; set; }
    }
}
