//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class clan
    {
        public long ClanId { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string Data { get; set; }
    }
}
